<h1>Comment</h1>
<form action="<?= $this->getUrl('week3/comment/post') ?>" method="post">
    <input type="hidden" name="return_url" value="<?= Mage::helper('core/url')->getCurrentUrl() ?>"/>
    <textarea name="comment" row="4" cols="40"></textarea>
    <br>
    <button class="button btn-default" type="submit"><?= $this->__('Comment') ?></button>
</form>
<?php $comments = $this->getCollection() ?>
<?php foreach ($comments as $comment): ?>
    <div style="margin:10px"><?= $comment->getComment() ?></div>
<?php endforeach; ?>
